"""Intitial

Revision ID: d4c028ee7223
Revises: 
Create Date: 2020-05-31 11:13:32.071954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c028ee7223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'item_features',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__item_features'))
    )
    op.create_table(
        'items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__items'))
    )
    op.create_table(
        'user_features',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__user_features'))
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_table(
        'interactions',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk__interactions__item_id__items')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__interactions__user_id__users')),
        sa.PrimaryKeyConstraint('id', 'user_id', 'item_id', name=op.f('pk__interactions'))
    )
    op.create_table(
        'item_description',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('feature_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['feature_id'], ['item_features.id'], name=op.f('fk__item_description__feature_id__item_features')),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk__item_description__item_id__items')),
        sa.PrimaryKeyConstraint('id', 'item_id', 'feature_id', name=op.f('pk__item_description'))
    )
    op.create_table(
        'user_description',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('feature_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['feature_id'], ['user_features.id'], name=op.f('fk__user_description__feature_id__user_features')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__user_description__user_id__users')),
        sa.PrimaryKeyConstraint('id', 'user_id', 'feature_id', name=op.f('pk__user_description'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_description')
    op.drop_table('item_description')
    op.drop_table('interactions')
    op.drop_table('users')
    op.drop_table('user_features')
    op.drop_table('items')
    op.drop_table('item_features')
    # ### end Alembic commands ###
