"""Add cascade deletions

Revision ID: e6659ab3464d
Revises: ebf43a9c712b
Create Date: 2020-05-31 18:27:26.515730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6659ab3464d'
down_revision = 'ebf43a9c712b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__interactions__item_id__items', 'interactions', type_='foreignkey')
    op.drop_constraint('fk__interactions__user_id__users', 'interactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk__interactions__item_id__items'), 'interactions', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk__interactions__user_id__users'), 'interactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk__item_description__feature_id__item_features', 'item_description', type_='foreignkey')
    op.drop_constraint('fk__item_description__item_id__items', 'item_description', type_='foreignkey')
    op.create_foreign_key(op.f('fk__item_description__item_id__items'), 'item_description', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk__item_description__feature_id__item_features'), 'item_description', 'item_features', ['feature_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk__user_description__feature_id__user_features', 'user_description', type_='foreignkey')
    op.drop_constraint('fk__user_description__user_id__users', 'user_description', type_='foreignkey')
    op.create_foreign_key(op.f('fk__user_description__user_id__users'), 'user_description', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk__user_description__feature_id__user_features'), 'user_description', 'user_features', ['feature_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__user_description__feature_id__user_features'), 'user_description', type_='foreignkey')
    op.drop_constraint(op.f('fk__user_description__user_id__users'), 'user_description', type_='foreignkey')
    op.create_foreign_key('fk__user_description__user_id__users', 'user_description', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk__user_description__feature_id__user_features', 'user_description', 'user_features', ['feature_id'], ['id'])
    op.drop_constraint(op.f('fk__item_description__feature_id__item_features'), 'item_description', type_='foreignkey')
    op.drop_constraint(op.f('fk__item_description__item_id__items'), 'item_description', type_='foreignkey')
    op.create_foreign_key('fk__item_description__item_id__items', 'item_description', 'items', ['item_id'], ['id'])
    op.create_foreign_key('fk__item_description__feature_id__item_features', 'item_description', 'item_features', ['feature_id'], ['id'])
    op.drop_constraint(op.f('fk__interactions__user_id__users'), 'interactions', type_='foreignkey')
    op.drop_constraint(op.f('fk__interactions__item_id__items'), 'interactions', type_='foreignkey')
    op.create_foreign_key('fk__interactions__user_id__users', 'interactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk__interactions__item_id__items', 'interactions', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
